model_name: gpt2-large
max_seq_length: 1024
num_train_epochs: 3
max_steps: -1
logging_steps: 10
eval_steps: 100
save_steps: 500
bf16: True
packing: False
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
dataset_text_field: "text"
use_gradient_checkpointing: False
use_flash_attn: False
