model_name: gpt2-large
max_seq_length: 1024
max_steps: 15000
logging_steps: 10
eval_steps: 100
save_steps: 500
bf16: True
packing: False
output_dir: "outputs/gpt2"
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
dataset_text_field: "text"
use_gradient_checkpointing: False
use_flash_attn: False
