model_name: gpt2-large
max_seq_length: 1024
max_steps: 15000
logging_steps: 10
eval_steps: 100
save_steps: 500
bf16: True
packing: False
output_dir: "outputs/gpt2"
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
dataset_text_field: "text"
use_gradient_checkpointing: False
use_flash_attn: False
dataset_name: wikimedia/wikipedia
dataset_subset: 20231101.fi
num_workers: 16
dataset_filter: 1000000
